# config/config_RAPID.yaml

# =======================================
#           PATHS TO IMAGES
# =======================================
# for demo, provide paths to .../data/demo/example_query and .../data/demo/example_database

q_imgs: ".../Real-time_Animal_reID/data/demo/example_database"    # path to query images
db_imgs: ".../Real-time_Animal_reID/data/demo/example_database"   # path to database images


# =======================================
#         optional configs below
# =======================================
# defaults are set here

# by providing these paths, you can skip calculations again
db_annoy_index_path: ""                 # path to ANN index (optional)
idx_map_path: ""                        # path to index map (optional)
closed_correct_ratios_path: ""          # path to closed correct ratios (optional)
closed_false_ratios_path: ""            # path to closed false ratios (optional)
open_ratios_path: ""                    # path to open ratios (optional)

# fine-tuning parameters
nr_kps: 150                             # number of keypoints to extract
topN_ids_match: 10                      # top-N retrieved IDs to consider
conf_score_limit: 500                   # number of matches used for confidence score calculation
conf_threshold: 0.5                     # confidence threshold
extend_db_while_proc: false             # extend database while processing
